CREATE TABLE wall (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`user` VARCHAR(20) NOT NULL DEFAULT 'Guest',
	`message` VARCHAR(255) NOT NULL,
	`dtg` DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY(`id`)
) Engine=InnoDB DEFAULT charset=utf8mb4;